# Server 설정
server:
  port: 9092

# Config 설정
spring:
  application:
    name: api1
  profiles:
    active: datasource-local, environment-local
  config:
    import: "optional:configserver:http://localhost:9091/" # Spring Cloud Config server 설정

# Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: "*"
