# server 설정
server:
  port: 9091

# config 설정
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tychejin1218/spring-cloud-config-properties
          default-label: main

# actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
