# server 설정
server:
  port: 9091

# config 설정
spring:
  application:
    name: spring-cloud-config-properties
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tychejin1218/spring-cloud-config-properties
#          uri: https://tychejin1218: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@github.com/tychejin1218/spring-cloud-config-properties.git
          search-paths: /api1/**, /api2/**
          default-label: main

# actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
